import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";



const osw = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio - Ely Wandeu ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${osw.variable}`}>
      <head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-BPVWM1DD3D"></script>
      </head>
         
      <body className="bg-[hsl(var(--background))] text-[hsl(var(--foreground))]">
        {children}
      </body>
    </html>
  );
}
